load("@envoy_api//bazel:api_build_system.bzl", "api_proto_package")

api_proto_package(
    deps = [
        "@com_github_cncf_udpa//udpa/annotations:pkg",
        "@envoy_api//envoy/config/core/v3:pkg",
        "//filters/api/envoy/extensions/filters/http/common/strong_matcher/v3:pkg",
        "@envoy_api//envoy/config/route/v3:pkg",
    ],
)
