load(
    "//bazel:envoy_build_system.bzl",
    "envoy_cc_library",
    "envoy_package",
)

licenses(["notice"])  # Apache 2

envoy_package()

envoy_cc_library(
    name = "regex_interface",
    hdrs = [
        "regex.h",
        "regex_matcher.h",
        "regex_replacer.h",
    ],
    deps = [
    ],
)
