admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9903
node:
  id: default~local
  cluster: xds-cluster
  metadata:
    role: default~local
dynamic_resources:
  lds_config:
    path: /root/envoy-filters/config/plugin_manager_lds.yaml

static_resources:
  clusters:
  - name: cluster.public_libs_service
    type: STRICT_DNS
    http2_protocol_options:
      max_concurrent_streams: 100
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cluster.public_libs_service
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 29210

  - name: cluster.central-database
    type: STRICT_DNS
    http2_protocol_options:
      max_concurrent_streams: 100
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cluster.central-database
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 7878

  - name: service_local_test
    type: STRICT_DNS
    lb_policy: RANDOM
    connect_timeout: 0.25s
    dns_lookup_family: V4_ONLY
    common_http_protocol_options: {}
    load_assignment:
      cluster_name: service_local_test # 集群的名称
      endpoints: # 需要进行负载均衡的端点列表
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    #如果不配置主机头重写，envoy不会改主机头
                    #nginx反向代理则会默认改写主机头为反向代理的地址
                    address: 127.0.0.1 #www.zyx.com #127.0.0.1 #192.192.101.45
                    port_value: 44433 #44433 #8000 #8889
# 7/9 xiaoy
layered_runtime:
  layers:
    - name: srhino_plugins_layer
      rtds_layer:
        name: srhino_plugins
        rtds_config:
          resource_api_version: V3
          path: /root/envoy-filters/config/resources_plugins.yaml
    - name: grpc_async_client_layer
      static_layer:
        envoy:
          reloadable_features:
            enable_grpc_async_client_cache: true
