syntax = "proto3";

package envoy.extensions.filters.http.weak_password_check.v3;

import "udpa/annotations/status.proto";
import "validate/validate.proto";

option java_package = "io.envoyproxy.envoy.extensions.filters.http.weak_password_check.v3";
option java_outer_classname = "WeakPasswordCheckProto";
option java_multiple_files = true;
option go_package = "github.com/ouryun/envoy/filters/api/envoy/extensions/filters/http/weak_password_check/v3;weak_password_checkv3";
option (udpa.annotations.file_status).package_version_status = ACTIVE;

message AdvanceConfig {
  // 用户名字段
  repeated string user_name = 1;
  // 密码字段
  repeated string password_name = 2;
  // 业务
  repeated string cluster_name = 3 [(validate.rules).repeated .items.string = {min_len: 1}];
}

enum DateFormat {
  Placeholder = 0x0000000000000000; // 无意义，占位而已
  YearMonthDay = 0x0000000000000001;
  YearMonth = 0x0000000000000002;
  MonthDay = 0x0000000000000004;
  Year = 0x0000000000000008;
  Month = 0x0000000000000010;
  Day = 0x0000000000000020;
}

message RuleConfig {
  repeated string part_rule = 1;
}

message CustomPassword {
  // 规则配置
  repeated RuleConfig rule_config = 1;
  // 日期范围
  repeated string date_range = 2;
  // 日期格式
  fixed32 date_format = 3;
  //插件实例名
  string filter_instance_id = 4;
}



message WeakPasswordCheckGlobal {
  // 自动 true:启用 false:禁用
  bool auto_mode = 1;
  // 高级配置
  repeated AdvanceConfig advance_config = 2;
  // 自定义弱密码库配置
  CustomPassword custom_password = 3;
}

message WeakPasswordCheckRoute {
}