syntax = "proto3";

package envoy.extensions.filters.http.weak_password_check.v3;

import "udpa/annotations/status.proto";
import "validate/validate.proto";

option java_package = "io.envoyproxy.envoy.extensions.filters.http.weak_password_check.v3";
option java_outer_classname = "WeakPasswordCheckProto";
option java_multiple_files = true;
option go_package = "github.com/ouryun/envoy/filters/api/envoy/extensions/filters/http/weak_password_check/v3;weak_password_checkv3";
option (udpa.annotations.file_status).package_version_status = ACTIVE;

enum TrigRuleType {
  TrigNone = 0; // 无匹配，强密码
  TrigInternal = 1; // 内置弱密码
  TrigCustom = 2; // 自定义弱密码
}

message ResultInfo {
  // 弱密码检测结果 true:弱密码 false:强密码
  bool is_weak_password = 1;
  // 密码是否为明文 
  bool is_plain_text=2;
  // 用户名
  string user_name = 3 [(validate.rules).string = {min_len: 1}];
  // 密码
  string password = 4 [(validate.rules).string = {min_len: 1}];
  // 请求路径
  string path = 5 [(validate.rules).string = {min_len: 1}];
  // 触发规则类型
  TrigRuleType trig_type = 6 [(validate.rules).enum = {defined_only: true}];
}

message WeakPasswordLog {
  // 检测结果
  repeated ResultInfo result_info = 1;
}