load(
    "//bazel:srhino_build_system.bzl",
    "srhino_cc_library",
)
package(default_visibility = ["//visibility:public"])

srhino_cc_library(
    name = "utility_lib",
    repository = "@envoy",
    srcs = [],
    hdrs = ["utility.h"],
    deps = [
    ],
)
