load(
    "//bazel:envoy_build_system.bzl",
    "envoy_cc_library",
    "envoy_package",
)

licenses(["notice"])  # Apache 2

envoy_package()

envoy_cc_library(
    name = "public_lib_interface",
    hdrs = [
        "cache.h",
        "public_lib.h",
    ],
    deps = [
    ],
)
