load("@envoy_api//bazel:api_build_system.bzl", "api_proto_package")

api_proto_package(
    deps = [
        "//envoy/srhino_plugin_framework/v1_3_x/proto/config/type:pkg",
        "//envoy/srhino_plugin_framework/v1_3_x/proto/config/core:pkg",
    ],
)
