load(
    "//bazel:envoy_build_system.bzl",
    "envoy_cc_library",
    "envoy_package",
)

licenses(["notice"])  # Apache 2

envoy_package()

envoy_cc_library(
    name = "utility_interface",
    hdrs = [
        "empty_string.hpp",
        "hash.hpp",
        "hex.hpp",
        "http_code.hpp",
        "http_parser.hpp",
        "hash_table.hpp",
        "net_address.hpp",
        "proto_tools.hpp",
        "singleton.hpp",
        "string_util.hpp",
        "url.hpp",
        "json.hpp",
    ],
    deps = [
    ],
)
